services:
- type: web 
  name: bitecult-backend
  env: python
  plan: free
  buildCommand: ""
  startCommand: uvicorn backend.app.main:app --host 0.0.0.0 --port 1000
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: recipe_app_db
        property: connectionString
